'use server'

import { client } from '@/lib/db';
import type { User } from '@/types/entities';

/**
 * Create a new user in the database
 * Returns the user with auto-generated ID
 */
export async function createUser(name: string): Promise<User> {
  const createdAt = new Date().toISOString();
  const result = await client.execute({
    sql: 'INSERT INTO users (name, created_at) VALUES (?, ?) RETURNING id, name, created_at',
    args: [name, createdAt]
  });
  
  if (!result.rows || result.rows.length === 0) {
    throw new Error('Failed to create user: No data returned from database');
  }
  
  const row = result.rows[0];
  const userId = Number(row.id);
  
  // Validate the ID is a valid positive integer (SQLite AUTOINCREMENT starts at 1)
  if (!userId || userId <= 0 || !Number.isInteger(userId)) {
    console.error('Invalid user ID returned from database:', row.id, 'parsed as:', userId);
    throw new Error('Failed to create user: Invalid ID generated by database');
  }
  
  return {
    id: userId,
    name: row.name as string,
    createdAt: row.created_at as string,
  };
}

/**
 * Get a user by ID
 */
export async function getUserById(id: number): Promise<User | null> {
  const result = await client.execute({
    sql: 'SELECT * FROM users WHERE id = ?',
    args: [id]
  });
  
  if (result.rows.length === 0) return null;
  
  const row = result.rows[0];
  return {
    id: Number(row.id),
    name: row.name as string,
    createdAt: row.created_at as string,
  };
}

/**
 * Get all users
 */
export async function getAllUsers(): Promise<User[]> {
  const result = await client.execute('SELECT * FROM users ORDER BY created_at ASC');
  return result.rows.map(row => ({
    id: Number(row.id),
    name: row.name as string,
    createdAt: row.created_at as string,
  }));
}

/**
 * Update a user's name
 */
export async function updateUserName(id: number, name: string): Promise<User | null> {
  await client.execute({
    sql: 'UPDATE users SET name = ? WHERE id = ?',
    args: [name, id]
  });
  
  return getUserById(id);
}

/**
 * Delete a user
 */
export async function deleteUser(id: number): Promise<boolean> {
  await client.execute({
    sql: 'DELETE FROM users WHERE id = ?',
    args: [id]
  });
  return true;
}

